CREATE TABLE notes (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name TEXT NOT NULL,
        content TEXT,
        folder_id INTEGER
        REFERENCES folders(id) ON DELETE CASCADE NOT NULL,
        date_modified TIMESTAMP DEFAULT now() NOT NULL 
);